import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type SiteTheme = "light" | "dark";
export type SiteLanguage = "en" | "id";

const translations: Record<string, string> = {
  "Home": "Beranda",
  "Destinations": "Destinasi",
  "Investment Opportunities": "Peluang Investasi",
  "Regulations": "Regulasi",
  "Newsletter": "Publikasi",
  "Contact Us": "Hubungi Kami",
  "Explore Opportunities": "Jelajahi Peluang",
  "Close menu": "Tutup menu",
  "Open menu": "Buka menu",
  "Navigate": "Navigasi",
  "Indonesia Tourism Investment": "Investasi Pariwisata Indonesia",
  "Invest in Indonesiaâ€™s": "Berinvestasi di",
  "Tourism Destinations": "Destinasi Pariwisata Indonesia",
  "Discover regenerative and priority tourism destinations with opportunities for sustainable development, investment, and long-term economic growth.": "Temukan destinasi pariwisata regeneratif dan prioritas dengan peluang pengembangan berkelanjutan, investasi, dan pertumbuhan ekonomi jangka panjang.",
  "Explore Destinations": "Jelajahi Destinasi",
  "Indonesia tourism destinations": "Destinasi pariwisata Indonesia",
  "Explore 13 strategic destinations": "Jelajahi 13 destinasi strategis",
  "Discover regenerative and priority tourism areas, their distinctive character, and potential investment themes.": "Jelajahi kawasan pariwisata regeneratif dan prioritas, karakter khasnya, serta tema potensi investasinya.",
  "Destination not found": "Destinasi tidak ditemukan",
  "Back to destinations": "Kembali ke destinasi",
  "destination": "destinasi",
  "All destinations": "Semua destinasi",
  "Destination overview": "Gambaran destinasi",
  "A distinctive place to explore and invest": "Tempat dengan keunikan untuk dijelajahi dan dikembangkan",
  "Tourism themes": "Tema pariwisata",
  "Key areas": "Kawasan utama",
  "Investment focus": "Fokus investasi",
  "Build on local strengths": "Bertumpu pada kekuatan lokal",
  "Potential sectors": "Sektor potensial",
  "Tourism investment sectors": "Sektor investasi pariwisata",
  "Investment ideas are indicative and should be assessed against local plans, regulations, and verified project information.": "Gagasan investasi ini bersifat indikatif dan perlu ditinjau berdasarkan rencana daerah, regulasi, serta informasi proyek yang telah diverifikasi.",
  "Explore further": "Jelajahi lebih lanjut",
  "Discuss opportunities in this destination": "Diskusikan peluang di destinasi ini",
  "Contact the tourism investment team to discuss destination information and potential collaboration.": "Hubungi tim investasi pariwisata untuk membahas informasi destinasi dan potensi kerja sama.",
  "Contact us": "Hubungi kami",
  "Explore Investment Opportunities": "Jelajahi Peluang Investasi",
  "Regenerative Destinations": "Destinasi Regeneratif",
  "Priority Destinations": "Destinasi Prioritas",
  "Strategic Tourism Destinations": "Destinasi Pariwisata Strategis",
  "Tourism Investment Landscape": "Peta Investasi Pariwisata",
  "Why You Should Invest in Indonesia’s Tourism?": "Peta Investasi Pariwisata Indonesia",
  "Indonesia's tourism landscape offers diverse opportunities across destinations with different geographic, cultural, environmental, and economic characteristics.": "Pariwisata Indonesia menawarkan beragam peluang di berbagai destinasi dengan karakter geografis, budaya, lingkungan, dan ekonomi yang berbeda.",
  "This portal provides an overview of regenerative and priority tourism destinations, helping investors and stakeholders explore tourism potential and investment opportunities across Indonesia.": "Portal ini menyajikan gambaran destinasi pariwisata regeneratif dan prioritas untuk membantu investor serta pemangku kepentingan menjajaki potensi dan peluang investasi di seluruh Indonesia.",
  "Explore the Destination Landscape": "Jelajahi Peta Destinasi",
  "Explore Tourism Investment Themes": "Jelajahi Tema Investasi Pariwisata",
  "Why Invest in Indonesiaâ€™s Tourism?": "Mengapa Berinvestasi di Pariwisata Indonesia?",
  "Contact & Investment Inquiries": "Kontak & Pertanyaan Investasi",
  "Have questions about tourism investment opportunities or destination development? Get in touch with our team.": "Punya pertanyaan tentang peluang investasi pariwisata atau pengembangan destinasi? Hubungi tim kami.",
  "Diverse Tourism Landscape": "Lanskap Pariwisata Beragam",
  "Strategic Connectivity": "Konektivitas Strategis",
  "Government Support": "Dukungan Pemerintah",
  "Sustainable Development": "Pembangunan Berkelanjutan",
  "Explore": "Jelajahi",
  "Search destination...": "Cari destinasi...",
  "All": "Semua",
  "Regenerative": "Regeneratif",
  "Priority": "Prioritas",
  "Marine": "Bahari",
  "Nature": "Alam",
  "Culture": "Budaya",
  "Wellness": "Kebugaran",
  "Urban": "Perkotaan",
  "Adventure": "Petualangan",
  "destinations": "destinasi",
  "Stay informed": "Tetap Terinformasi",
  "Why You Should Invest in Indonesia’s Tourism?": "Ikuti Perkembangan Investasi Pariwisata Indonesia",
  "Get the latest destination insights, tourism investment opportunities, policy updates, and strategic developments.": "Dapatkan informasi terbaru tentang destinasi, peluang investasi pariwisata, kebijakan, dan perkembangan strategis.",
  "Email address": "Alamat email",
  "Enter your email address": "Masukkan alamat email",
  "Sign Me Up": "Daftar Sekarang",
  "Full Name": "Nama Lengkap",
  "Organization": "Organisasi",
  "Email": "Email",
  "Phone": "Telepon",
  "Destination": "Destinasi",
  "Choose a destination": "Pilih destinasi",
  "Investment Sector": "Sektor Investasi",
  "Choose a sector": "Pilih sektor",
  "Hospitality": "Akomodasi",
  "Marine Tourism": "Pariwisata Bahari",
  "Creative Economy": "Ekonomi Kreatif",
  "Message": "Pesan",
  "Submit Inquiry": "Kirim Pertanyaan",
  "View Opportunity": "Lihat Peluang",
  "Investment type": "Jenis investasi",
  "Sector": "Sektor",
  "Laws & Regulations": "Hukum & Regulasi",
  "A practical introduction to the rules shaping tourism investment, project licensing, and destination development in Indonesia.": "Pengantar praktis mengenai aturan investasi pariwisata, perizinan proyek, dan pengembangan destinasi di Indonesia.",
  "Explore the framework": "Jelajahi kerangka regulasi",
  "Introduction": "Pengantar",
  "Build with a clear view of the rules.": "Bangun proyek dengan memahami regulasi.",
  "Tourism projects sit at the intersection of investment, business licensing, destination planning, and environmental management. The right requirements depend on what you plan to do and where you plan to do it.": "Proyek pariwisata berkaitan dengan investasi, perizinan usaha, perencanaan destinasi, dan pengelolaan lingkungan. Persyaratan yang berlaku bergantung pada jenis kegiatan dan lokasi proyek.",
  "Use this guide to find the main national regulations and official services, then confirm the details for your project with the relevant authorities.": "Gunakan panduan ini untuk menemukan regulasi nasional dan layanan resmi, lalu konfirmasikan persyaratan proyek kepada instansi terkait.",
  "Browse key regulations": "Telusuri regulasi utama",
  "The framework": "Kerangka Regulasi",
  "Key regulations for tourism investment": "Regulasi Utama Investasi Pariwisata",
  "Open a topic for a short overview and links to the official regulation or service.": "Pilih topik untuk melihat ringkasan dan tautan ke regulasi atau layanan resmi.",
  "Start with your activity and location": "Mulai dari kegiatan dan lokasi proyek",
  "The applicable process may vary by KBLI, risk level, project scale, site, and environmental impact.": "Proses yang berlaku dapat berbeda berdasarkan KBLI, tingkat risiko, skala proyek, lokasi, dan dampak lingkungan.",
  "Find tourism investment opportunities across Indonesia.": "Temukan peluang investasi pariwisata di seluruh Indonesia.",
  "Featured Projects": "Proyek Unggulan",
  "Project Classification": "Klasifikasi Proyek",
  "Thematic Opportunities": "Peluang Tematik",
  "Straight from our investors": "Cerita dari Investor",
  "Explore projects": "Jelajahi Proyek",
  "Filter by": "Filter berdasarkan",
  "Investment value": "Nilai investasi",
  "Ownership": "Kepemilikan",
  "Thematic": "Tematik",
  "Recent Publications": "Publikasi Terbaru",
  "Curated updates on investment performance, tourism-sector data, and destination developmentâ€”paired with concise PDF briefs and links to the original sources.": "Informasi pilihan tentang realisasi investasi, data sektor pariwisata, dan pengembangan destinasi, dilengkapi ringkasan PDF dan tautan sumber resmi.",
  "Research desk": "Pusat Riset",
  "Browse the library": "Telusuri Pustaka",
  "All publications": "Semua publikasi",
  "National investment": "Investasi nasional",
  "Tourism investment data": "Data investasi pariwisata",
  "Destination spotlight": "Sorotan destinasi",
  "Investment insights & updates": "Wawasan & kabar investasi",
  "Read official source": "Baca sumber resmi",
  "Download PDF": "Unduh PDF",
  "Preview": "Pratinjau",
  "Continue your research": "Lanjutkan riset Anda",
  "Explore original reports and open data": "Jelajahi laporan lengkap dan data terbuka",
  "See more": "Lihat selengkapnya",
  "We are here to help": "Kami siap membantu",
  "Connect with the Ministry of Tourism for destination information, tourism investment inquiries, and official support channels.": "Hubungi Kementerian Pariwisata untuk informasi destinasi, pertanyaan investasi pariwisata, dan layanan resmi.",
  "Contact & inquiries": "Kontak & pertanyaan",
  "Letâ€™s start a conversation.": "Mari mulai percakapan.",
  "Official channels": "Kanal resmi",
  "Contact the Ministry": "Hubungi Kementerian",
  "Visit us": "Kunjungi kami",
  "Open map": "Buka peta",
  "Chat on WhatsApp": "Chat melalui WhatsApp",
  "Call now": "Telepon sekarang",
  "Send an email": "Kirim email",
  "Call the Ministry": "Telepon Kementerian",
  "Send an investment inquiry": "Kirim pertanyaan investasi",
  "Need help with an OSS application?": "Butuh bantuan layanan OSS?",
  "OSS Call Center Â· 169": "Pusat Panggilan OSS Â· 169",
  "Indonesia Â· Investor guide": "Indonesia Â· Panduan Investor",
  "One project Â· Several checks": "Satu proyek Â· Beberapa aspek",
  "Tourism policy & governance": "Kebijakan & tata kelola pariwisata",
  "Investment framework & facilities": "Kerangka & fasilitas investasi",
  "Risk-based business licensing": "Perizinan berusaha berbasis risiko",
  "Location & environmental approvals": "Persetujuan lokasi & lingkungan",
  "Regenerative destinations Â· 01": "Destinasi regeneratif Â· 01",
  "Priority destinations Â· 02": "Destinasi prioritas Â· 02",
  "Destination ecosystem": "Ekosistem destinasi",
  "The investment case": "Alasan berinvestasi",
  "Why invest in Indonesia tourism?": "MENGAPA BERINVESTASI DI PARIWISATA INDONESIA?",
  "Why invest in Indonesia's tourism?": "MENGAPA BERINVESTASI DI PARIWISATA INDONESIA?",
  "Why You Should Invest in Indonesia’s Tourism?": "Mengapa Anda Perlu Berinvestasi di Pariwisata Indonesia?",
  "Discover Indonesia": "Jelajahi Indonesia",
  "A closer look at Indonesia’s tourism potential": "Melihat Lebih Dekat Potensi Pariwisata Indonesia",
  "Explore the natural beauty, cultural heritage, and local stories that make Indonesia a remarkable place to visit and invest.": "Jelajahi keindahan alam, warisan budaya, dan kisah lokal yang menjadikan Indonesia tempat istimewa untuk dikunjungi dan berinvestasi.",
  "Watch on YouTube": "Tonton di YouTube",
  "Starts muted when visible and pauses when you scroll away": "Video dimulai tanpa suara saat terlihat dan berhenti ketika Anda menggulir menjauh",
  "Discover the opportunities behind the growth of tourism investment in Indonesia.": "Jelajahi peluang di balik pertumbuhan investasi pariwisata Indonesia.",
  "Tourism in Indonesia is full of potential, driven by global demand for authentic and diverse travel experiences. Here are five reasons to invest.": "Pariwisata Indonesia memiliki potensi besar, didorong oleh permintaan global akan pengalaman perjalanan yang autentik dan beragam. Berikut lima alasannya untuk berinvestasi.",
  "Discover the opportunities behind Indonesia's growing tourism investment landscape.": "Jelajahi peluang di balik perkembangan lanskap investasi pariwisata Indonesia.",
  "Favourable Business Climate": "Iklim Usaha yang Kondusif",
  "A supportive policy environment helps tourism businesses plan and grow with confidence.": "Lingkungan kebijakan yang mendukung membantu bisnis pariwisata merencanakan dan tumbuh dengan percaya diri.",
  "Air, sea, and land links connect visitors to destinations across the archipelago.": "Konektivitas udara, laut, dan darat menghubungkan wisatawan dengan destinasi di seluruh nusantara.",
  "Nature, culture, marine, wellness, gastronomy, and urban experiences create many paths to invest.": "Pengalaman alam, budaya, bahari, kebugaran, kuliner, dan perkotaan membuka beragam jalur investasi.",
  "Young & Productive Talent": "Talenta Muda dan Produktif",
  "A dynamic workforce brings energy, skills, and local knowledge to tourism growth.": "Tenaga kerja yang dinamis membawa energi, keterampilan, dan pengetahuan lokal bagi pertumbuhan pariwisata.",
  "Untapped Niche Potential": "Potensi Ceruk yang Belum Tergarap",
  "Emerging specialist experiences open room for distinctive, high-quality development.": "Pengalaman wisata khusus yang berkembang membuka ruang bagi pengembangan yang khas dan berkualitas.",
  "Thematic opportunities": "Peluang tematik",
  "Sample portfolio": "Contoh portofolio",
  "Portfolio pathways": "Klasifikasi portofolio",
  "Knowledge & insight": "Wawasan & informasi",
  "Latest Publications": "Publikasi Terbaru",
  "Investor perspectives": "Perspektif investor",
  "Straight from Our Investors": "Cerita Langsung dari Investor",
  "Start a conversation": "Mari berdiskusi",
  "Primary navigation": "Navigasi utama",
  "Choose language": "Pilih bahasa",
  "Switch to dark mode": "Aktifkan mode gelap",
  "Switch to light mode": "Aktifkan mode terang",
  "destination": "destinasi",
  "Search destination": "Cari destinasi",
  "Tourism Investment Opportunities": "Peluang Investasi Pariwisata",
  "Indonesia · Tourism investment": "Indonesia · Investasi pariwisata",
  "Explore project concepts and discover where investment can support high-quality, sustainable tourism across Indonesia.": "Jelajahi konsep proyek dan temukan peluang investasi yang mendukung pariwisata berkualitas dan berkelanjutan di seluruh Indonesia.",
  "Search investment project concepts": "Cari konsep proyek investasi",
  "Search projects, destinations, or sectors...": "Cari proyek, destinasi, atau sektor...",
  "Explore featured projects": "Jelajahi proyek unggulan",
  "Explore the pipeline": "Jelajahi portofolio",
  "Featured project concepts": "Konsep proyek unggulan",
  "project concept": "konsep proyek",
  "project concepts": "konsep proyek",
  "These project concepts are illustrative examples, not live offers or confirmed government projects. Investment values and official project details will be published when verified information is available.": "Konsep proyek ini merupakan contoh ilustratif, bukan penawaran aktif atau proyek pemerintah yang telah dikonfirmasi. Nilai investasi dan detail resmi akan dipublikasikan setelah informasinya terverifikasi.",
  "Tourism opportunities can be advanced by different owners and delivery partners. Understanding the project context helps identify the right counterpart and next steps.": "Peluang pariwisata dapat dikembangkan oleh berbagai pemilik dan mitra pelaksana. Memahami konteks proyek membantu menentukan mitra dan langkah selanjutnya.",
  "Public destination bodies coordinate strategy, destination priorities, and investment pathways with partners.": "Badan pengelola destinasi publik mengoordinasikan strategi, prioritas destinasi, dan jalur investasi bersama para mitra.",
  "Designated areas can offer an integrated setting for tourism, supporting infrastructure, and related business activity.": "Kawasan yang ditetapkan dapat menyediakan lingkungan terpadu bagi pariwisata, infrastruktur pendukung, dan kegiatan usaha terkait.",
  "Businesses can develop hospitality, visitor experiences, and supporting services in partnership with local stakeholders.": "Pelaku usaha dapat mengembangkan akomodasi, pengalaman wisata, dan layanan pendukung bersama pemangku kepentingan setempat.",
  "Explore sectors that connect Indonesia’s destination strengths with infrastructure, visitor experiences, and local enterprise.": "Jelajahi sektor yang menghubungkan keunggulan destinasi Indonesia dengan infrastruktur, pengalaman wisata, dan usaha lokal.",
  "Coastal, island, and water-based destination development.": "Pengembangan destinasi pesisir, pulau, dan wisata perairan.",
  "Restorative experiences rooted in place, nature, and culture.": "Pengalaman pemulihan yang berakar pada tempat, alam, dan budaya.",
  "Culinary destinations and regionally distinctive food experiences.": "Destinasi kuliner dan pengalaman makanan khas daerah.",
  "Featured destination areas": "Kawasan destinasi unggulan",
  "Discover high-potential destinations across Indonesia.": "Jelajahi destinasi berpotensi tinggi di seluruh Indonesia.",
  "Explore places where local character, visitor demand, and responsible investment can come together.": "Jelajahi kawasan tempat keunikan lokal, kebutuhan wisatawan, dan investasi bertanggung jawab dapat berjalan bersama.",
  "Wellness, culture & regenerative stays": "Kebugaran, budaya, dan akomodasi regeneratif",
  "Nature, marine & destination experiences": "Alam, bahari, dan pengalaman destinasi",
  "Urban tourism, hospitality & MICE": "Wisata perkotaan, akomodasi, dan MICE",
  "Explore destination": "Jelajahi destinasi",
  "View investment concepts": "Lihat konsep investasi",
  "Project opportunity pipeline": "Rangkaian peluang proyek",
  "The investor perspective": "Perspektif investor",
  "What makes a destination investment-ready?": "Apa yang membuat destinasi siap untuk investasi?",
  "A strong tourism opportunity connects destination needs with a clear, responsible path to long-term value.": "Peluang pariwisata yang kuat menghubungkan kebutuhan destinasi dengan langkah yang jelas dan bertanggung jawab menuju nilai jangka panjang.",
  "Destination readiness": "Kesiapan destinasi",
  "Clear plans, access, and supporting infrastructure help move promising ideas toward delivery.": "Rencana, akses, dan infrastruktur pendukung yang jelas membantu mewujudkan gagasan yang menjanjikan.",
  "Distinctive experiences": "Pengalaman yang khas",
  "Investment can build on the local character, culture, and natural assets of each destination.": "Investasi dapat bertumpu pada karakter lokal, budaya, dan kekayaan alam setiap destinasi.",
  "Long-term value": "Nilai jangka panjang",
  "Responsible development strengthens tourism quality, resilience, and community participation.": "Pengembangan yang bertanggung jawab memperkuat kualitas dan ketahanan pariwisata serta partisipasi masyarakat.",
  "Browse illustrative opportunities across priority and regenerative destinations. Filter by destination type, investment approach, or sector.": "Jelajahi contoh peluang di destinasi prioritas dan regeneratif. Saring berdasarkan jenis destinasi, pendekatan investasi, atau sektor.",
  "Let’s start a conversation.": "Mari mulai percakapan.",
  "Our contact channels can help you find the right starting point for questions about Indonesia’s tourism destinations, investment opportunities, and Ministry information.": "Kanal kontak kami membantu Anda menemukan tujuan yang tepat untuk pertanyaan tentang destinasi pariwisata Indonesia, peluang investasi, dan informasi Kementerian.",
  "Use the official contact center for general inquiries. For a tourism investment proposal, include the destination, project type, and the best way to reach you.": "Gunakan pusat kontak resmi untuk pertanyaan umum. Untuk proposal investasi pariwisata, sertakan destinasi, jenis proyek, dan cara terbaik untuk menghubungi Anda.",
  "Business licensing support": "Dukungan perizinan usaha",
  "For technical support with Online Single Submission (OSS), use the OSS help channels directly. For policy or destination questions, contact the Ministry of Tourism.": "Untuk bantuan teknis Online Single Submission (OSS), hubungi kanal bantuan OSS. Untuk pertanyaan kebijakan atau destinasi, hubungi Kementerian Pariwisata.",
  "Our Websites": "Situs Kami",
  "Official information should be verified through the relevant government authorities and official publications.": "Informasi resmi perlu dikonfirmasi melalui instansi pemerintah dan publikasi terkait.",
  "Ministry of Tourism": "Kementerian Pariwisata",
  "Republic of Indonesia": "Republik Indonesia",
  "WhatsApp Contact Center": "Pusat Kontak WhatsApp",
  "Curated updates on investment performance, tourism-sector data, and destination development—paired with concise PDF briefs and links to the original sources.": "Informasi pilihan tentang realisasi investasi, data sektor pariwisata, dan pengembangan destinasi, dilengkapi ringkasan PDF dan tautan sumber resmi.",
  "destination type": "jenis destinasi",
  "Destination type": "Jenis destinasi",
  "Investment approach": "Pendekatan investasi",
  "All destinations": "Semua destinasi",
  "All approaches": "Semua pendekatan",
  "All sectors": "Semua sektor",
  "Private investment": "Investasi swasta",
  "Development partnership": "Kemitraan pengembangan",
  "Thematic sector": "Sektor tematik",
  "Illustrative concept": "Konsep ilustratif",
  "Discuss an opportunity": "Diskusikan peluang",
  "No project concepts match these filters.": "Tidak ada konsep proyek yang cocok dengan filter ini.",
  "Try a different destination, approach, or sector.": "Coba destinasi, pendekatan, atau sektor lain.",
  "Clear all filters": "Hapus semua filter",
  "Project classification": "Klasifikasi proyek",
  "Find the right pathway for your project.": "Temukan jalur yang tepat untuk proyek Anda.",
  "Contact the investment team": "Hubungi tim investasi",
  "Where tourism can grow": "Peluang pertumbuhan pariwisata",
  "From interest to investment conversation": "Dari ketertarikan menuju diskusi investasi",
  "Your next step": "Langkah berikutnya",
  "Define your sector": "Tentukan sektor",
  "Tourism authority boards": "Badan otoritas pariwisata",
  "Special economic zones": "Kawasan ekonomi khusus",
  "Private companies": "Perusahaan swasta",
  "Public sector": "Sektor publik",
  "Destination zones": "Kawasan destinasi",
  "Private sector": "Sektor swasta",
  "Tourism Investment in Indonesia": "Investasi Pariwisata Indonesia",
  "Invest in Indonesia Tourism Destinations": "Berinvestasi di Destinasi Pariwisata Indonesia",
 };

type Preferences = {
  theme: SiteTheme;
  language: SiteLanguage;
  setTheme: (theme: SiteTheme) => void;
  setLanguage: (language: SiteLanguage) => void;
  t: (english: string) => string;
};

const PreferencesContext = createContext<Preferences | null>(null);

export function SitePreferencesProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<SiteTheme>("light");
  const [language, setLanguage] = useState<SiteLanguage>("en");

  useEffect(() => {
    const savedTheme = localStorage.getItem("kemenpar-theme");
    const savedLanguage = localStorage.getItem("kemenpar-language");
    if (savedTheme === "light" || savedTheme === "dark") setTheme(savedTheme);
    if (savedLanguage === "en" || savedLanguage === "id") setLanguage(savedLanguage);
  }, []);

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    document.documentElement.style.colorScheme = theme;
    localStorage.setItem("kemenpar-theme", theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem("kemenpar-language", language);
  }, [language]);

  const value = useMemo(() => ({ theme, language, setTheme, setLanguage, t: (english: string) => language === "id" ? (translations[english] ?? english) : english }), [theme, language]);
  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function useSitePreferences() {
  const value = useContext(PreferencesContext);
  if (!value) throw new Error("useSitePreferences must be used within SitePreferencesProvider");
  return value;
}
